/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package ca.weblite.oscon2014.schedulebuilder.views;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class ScheduleListDetailsTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public ScheduleListDetailsTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BorderLayout rootLayout = new BorderLayout();
root.setLayout(rootLayout);
Container node1 = new Container();
BoxLayout node1Layout = new BoxLayout(BoxLayout.Y_AXIS);
node1.setLayout(node1Layout);
SpanLabel node2 = new SpanLabel();
node2.setName("eventName");
_nameIndex.put("eventName", node2);
node2.setText("Event Name");
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node2.getParent()){
node1.addComponent(node2);
}
Label node3 = new Label();
node3.setName("eventDate");
_nameIndex.put("eventDate", node3);
node3.setText("Event Date");
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node3.getParent()){
node1.addComponent(node3);
}
Label node4 = new Label();
node4.setName("eventLocation");
_nameIndex.put("eventLocation", node4);
node4.setText("Event Location");
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node4.getParent()){
node1.addComponent(node4);
}
SpanLabel node5 = new SpanLabel();
node5.setName("speakers");
_nameIndex.put("speakers", node5);
node5.setText("Speaker");
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node5.getParent()){
node1.addComponent(node5);
}
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(BorderLayout.NORTH, node1);
}
SpanLabel node6 = new SpanLabel();
node6.setName("eventDescription");
_nameIndex.put("eventDescription", node6);
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && root != node6.getParent()){
root.addComponent(BorderLayout.CENTER, node6);
}
return root;
}
public SpanLabel getEventName(){
      return (SpanLabel)get("eventName");
      }
public Label getEventDate(){
      return (Label)get("eventDate");
      }
public Label getEventLocation(){
      return (Label)get("eventLocation");
      }
public SpanLabel getSpeakers(){
      return (SpanLabel)get("speakers");
      }
public SpanLabel getEventDescription(){
      return (SpanLabel)get("eventDescription");
      }
}